name: TestAndBuild
on:
    push:
      branches: [ master ]
    pull_request:
      branches: [ master ]
jobs:
    testAndBuild:
      name: Test And Build Docker Iamge
      runs-on: ubuntu-latest
      steps:
       - uses: actions/checkout@v2
        # Setup .npmrc file to publish to npm
       - uses: actions/setup-node@v2
         with:
            node-version: '16.x'
            registry-url: 'https://registry.npmjs.org'
       - name: clean install
         run: npm ci
       - name: build
         run: npm run build

       - name: build docker Image
         run: |
             docker build  -t  ${{ secrets.CONTAINER_IAMGE_NAME }}  .
       - name: push the docker image
         env:
           HEROKU_API_KEY: ${{ secrets.CONTAINER_REGISTRY_API_KEY}}
         run: |
               docker login --username=${{ secrets.CONTAINER_REGISTRY_USER_NAME }} --password=${{ secrets.CONTAINER_REGISTRY_API_KEY}}  ${{ secrets.CONTAINER_REGISTRY }}
               docker tag ${{ secrets.CONTAINER_IAMGE_NAME }}  ${{ secrets.CONTAINER_REGISTRY }}/${{ secrets.HEROKU_APP_ANME }}/web
               docker push  ${{ secrets.CONTAINER_REGISTRY }}/${{ secrets.HEROKU_APP_ANME }}/web
               heroku container:release web -a ${{ secrets.HEROKU_APP_ANME }}


