name: TestAndBuild
on:
    push:
      branches: [ master ]
    pull_request:
      branches: [ master ]
jobs:
    testAndBuild:
      name: Test And Build Docker Iamge
      runs-on: ubuntu-latest
      steps:
       - uses: actions/checkout@v2
        # Setup .npmrc file to publish to npm
       - uses: actions/setup-node@v2
         with:
            node-version: '16.x'
            registry-url: 'https://registry.npmjs.org'
       - name: clean install
         run: npm ci
       - name: build
         run: npm run build

       - name: build docker Image
         run: |
             docker build  -t  scheduler-web  .
       - name: push the docker image
         run: |
               docker login --username=${{ secrets.HEROKU_USER_NAME }} --password=${{ secrets.HEROKU_API_KEY }} registry.heroku.com
               sudo docker push scheduler-web
               sudo docker tag scheduler-web scheduler-web-dev
               sudo heroku container:release scheduler-web-dev -a spring1-boot-app-dev

      outputs:
        image_name: scheduler-web

