name: TestAndBuild
on:
    push:
      branches: [ master ]
    pull_request:
      branches: [ master ]
jobs:
    testAndBuild:
      name: Test And Build Docker Iamge
      runs-on: ubuntu-latest
      steps:
       - uses: actions/checkout@v2
       - name: Log in to the Container registry
         uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
         with:
           registry: registry.heroku.com
           username: ${{ secrets.HEROKU_USER_NAME }}
           password: ${{ secrets.HEROKU_API_KEY }}

       - name: Extract metadata (tags, labels) for Docker
         id: meta
         uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
         with:
           images: registry.heroku.com/schedular-web

       - name: Build and push Docker image
         uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
         with:
           context: .
           push: true
           tags: ${{ steps.meta.outputs.tags }}
           labels: ${{ steps.meta.outputs.labels }}
        # Setup .npmrc file to publish to npm
       - uses: actions/setup-node@v2
         with:
            node-version: '16.x'
            registry-url: 'https://registry.npmjs.org'
       - name: clean install
         run: npm ci
       - name: build
         run: npm run build


      outputs:
        image_name: scheduler-web

